name: flutter_live_streaming_and_calls
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: 15.2.8
  zego_uikit: ^2.27.1
  zego_uikit_prebuilt_call: ^4.16.29
  zego_uikit_signaling_plugin: ^2.8.1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  provider: ^6.0.5
  share_plus: ^11.0.0
  zego_uikit_prebuilt_live_streaming: ^3.13.15
  geolocator: ^14.0.2
  lottie: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
