// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// NOTE: Replace the placeholder values below with your own Firebase project configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "YOUR_WEB_API_KEY",
    authDomain: "YOUR_WEB_AUTH_DOMAIN",
    projectId: "YOUR_WEB_PROJECT_ID",
    storageBucket: "YOUR_WEB_STORAGE_BUCKET",
    messagingSenderId: "YOUR_WEB_MESSAGING_SENDER_ID",
    appId: "YOUR_WEB_APP_ID",
    measurementId: "YOUR_WEB_MEASUREMENT_ID",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "YOUR_ANDROID_API_KEY",
    authDomain: "YOUR_ANDROID_AUTH_DOMAIN",
    projectId: "YOUR_ANDROID_PROJECT_ID",
    storageBucket: "YOUR_ANDROID_STORAGE_BUCKET",
    messagingSenderId: "YOUR_ANDROID_MESSAGING_SENDER_ID",
    appId: "YOUR_ANDROID_APP_ID",
    measurementId: "YOUR_ANDROID_MEASUREMENT_ID",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "YOUR_IOS_API_KEY",
    authDomain: "YOUR_IOS_AUTH_DOMAIN",
    projectId: "YOUR_IOS_PROJECT_ID",
    storageBucket: "YOUR_IOS_STORAGE_BUCKET",
    messagingSenderId: "YOUR_IOS_MESSAGING_SENDER_ID",
    appId: "YOUR_IOS_APP_ID",
    measurementId: "YOUR_IOS_MEASUREMENT_ID",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "YOUR_MACOS_API_KEY",
    authDomain: "YOUR_MACOS_AUTH_DOMAIN",
    projectId: "YOUR_MACOS_PROJECT_ID",
    storageBucket: "YOUR_MACOS_STORAGE_BUCKET",
    messagingSenderId: "YOUR_MACOS_MESSAGING_SENDER_ID",
    appId: "YOUR_MACOS_APP_ID",
    measurementId: "YOUR_MACOS_MEASUREMENT_ID",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "YOUR_WINDOWS_API_KEY",
    authDomain: "YOUR_WINDOWS_AUTH_DOMAIN",
    projectId: "YOUR_WINDOWS_PROJECT_ID",
    storageBucket: "YOUR_WINDOWS_STORAGE_BUCKET",
    messagingSenderId: "YOUR_WINDOWS_MESSAGING_SENDER_ID",
    appId: "YOUR_WINDOWS_APP_ID",
    measurementId: "YOUR_WINDOWS_MEASUREMENT_ID",
  );
}
