// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAUNYFRXsClJe2bfiJ_IDWbHpVM14u-8WE",
    authDomain: "html-6aa97.firebaseapp.com",
    projectId: "html-6aa97",
    storageBucket: "html-6aa97.appspot.com",
    messagingSenderId: "29341518763",
    appId: "1:29341518763:web:fd103ec55acf4a8f4120ee",
    measurementId: "G-SSF5C4DK0N",
  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: "AIzaSyAUNYFRXsClJe2bfiJ_IDWbHpVM14u-8WE",
    authDomain: "html-6aa97.firebaseapp.com",
    projectId: "html-6aa97",
    storageBucket: "html-6aa97.appspot.com",
    messagingSenderId: "29341518763",
    appId: "1:29341518763:web:fd103ec55acf4a8f4120ee",
    measurementId: "G-SSF5C4DK0N",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAUNYFRXsClJe2bfiJ_IDWbHpVM14u-8WE",
    authDomain: "html-6aa97.firebaseapp.com",
    projectId: "html-6aa97",
    storageBucket: "html-6aa97.appspot.com",
    messagingSenderId: "29341518763",
    appId: "1:29341518763:web:fd103ec55acf4a8f4120ee",
    measurementId: "G-SSF5C4DK0N",
  );

  static const FirebaseOptions macos = FirebaseOptions(
  apiKey: "AIzaSyAUNYFRXsClJe2bfiJ_IDWbHpVM14u-8WE",
  authDomain: "html-6aa97.firebaseapp.com",
  projectId: "html-6aa97",
  storageBucket: "html-6aa97.appspot.com",
  messagingSenderId: "29341518763",
  appId: "1:29341518763:web:fd103ec55acf4a8f4120ee",
  measurementId: "G-SSF5C4DK0N",
  );

  static const FirebaseOptions windows = FirebaseOptions(
  apiKey: "AIzaSyAUNYFRXsClJe2bfiJ_IDWbHpVM14u-8WE",
  authDomain: "html-6aa97.firebaseapp.com",
  projectId: "html-6aa97",
  storageBucket: "html-6aa97.appspot.com",
  messagingSenderId: "29341518763",
  appId: "1:29341518763:web:fd103ec55acf4a8f4120ee",
  measurementId: "G-SSF5C4DK0N",
  );
}
